# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGridLayout, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpacerItem, QTabWidget,
    QTextBrowser, QVBoxLayout, QWidget)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u":/assets/icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon1 = QIcon()
        if QIcon.hasThemeIcon(QIcon.ThemeIcon.EditCopy):
            icon1 = QIcon.fromTheme(QIcon.ThemeIcon.EditCopy)
        else:
            icon1.addFile(u"../../../../../../../.designer/backup", QSize(), QIcon.Normal, QIcon.Off)

        self.actionCopy.setIcon(icon1)
        self.actionCopy.setMenuRole(QAction.MenuRole.NoRole)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon2 = QIcon()
        if QIcon.hasThemeIcon(QIcon.ThemeIcon.EditPaste):
            icon2 = QIcon.fromTheme(QIcon.ThemeIcon.EditPaste)
        else:
            icon2.addFile(u"../../../../../../../.designer/backup", QSize(), QIcon.Normal, QIcon.Off)

        self.actionPaste.setIcon(icon2)
        self.actionPaste.setMenuRole(QAction.MenuRole.NoRole)
        self.actionEncode = QAction(MainWindow)
        self.actionEncode.setObjectName(u"actionEncode")
        self.actionEncode.setMenuRole(QAction.MenuRole.NoRole)
        self.actionDecode = QAction(MainWindow)
        self.actionDecode.setObjectName(u"actionDecode")
        self.actionDecode.setMenuRole(QAction.MenuRole.NoRole)
        self.actionBrute = QAction(MainWindow)
        self.actionBrute.setObjectName(u"actionBrute")
        self.actionBrute.setMenuRole(QAction.MenuRole.NoRole)
        self.actionOperationChanged = QAction(MainWindow)
        self.actionOperationChanged.setObjectName(u"actionOperationChanged")
        self.actionConfig = QAction(MainWindow)
        self.actionConfig.setObjectName(u"actionConfig")
        self.actionConfig.setMenuRole(QAction.MenuRole.NoRole)
        self.actionZoomIn = QAction(MainWindow)
        self.actionZoomIn.setObjectName(u"actionZoomIn")
        self.actionZoomIn.setMenuRole(QAction.MenuRole.NoRole)
        self.actionZoomOut = QAction(MainWindow)
        self.actionZoomOut.setObjectName(u"actionZoomOut")
        self.actionZoomOut.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(800, 578))
        self.centralwidget.setMaximumSize(QSize(800, 578))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 791, 581))
        self.tabWidget.setMinimumSize(QSize(791, 581))
        self.tabWidget.setMaximumSize(QSize(791, 581))
        self.tabWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.inputTab = QWidget()
        self.inputTab.setObjectName(u"inputTab")
        self.inputTab.setMinimumSize(QSize(787, 550))
        self.inputTab.setMaximumSize(QSize(787, 550))
        self.gridLayoutWidget_2 = QWidget(self.inputTab)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(0, 0, 791, 551))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.inputText = QPlainTextEdit(self.gridLayoutWidget_2)
        self.inputText.setObjectName(u"inputText")
        self.inputText.setMinimumSize(QSize(749, 439))
        self.inputText.setMaximumSize(QSize(749, 449))
        font = QFont()
        font.setPointSize(9)
        self.inputText.setFont(font)
        self.inputText.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.inputText.setBackgroundVisible(False)

        self.gridLayout_2.addWidget(self.inputText, 2, 0, 1, 1)

        self.btnPaste = QPushButton(self.gridLayoutWidget_2)
        self.btnPaste.setObjectName(u"btnPaste")
        self.btnPaste.setMinimumSize(QSize(201, 25))
        self.btnPaste.setMaximumSize(QSize(201, 25))
        self.btnPaste.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.btnPaste.setIcon(icon2)

        self.gridLayout_2.addWidget(self.btnPaste, 0, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.btnZoomIn = QPushButton(self.gridLayoutWidget_2)
        self.btnZoomIn.setObjectName(u"btnZoomIn")
        self.btnZoomIn.setMaximumSize(QSize(31, 25))
        font1 = QFont()
        font1.setPointSize(18)
        self.btnZoomIn.setFont(font1)

        self.horizontalLayout_2.addWidget(self.btnZoomIn)

        self.btnZoomOut = QPushButton(self.gridLayoutWidget_2)
        self.btnZoomOut.setObjectName(u"btnZoomOut")
        self.btnZoomOut.setMaximumSize(QSize(31, 25))
        self.btnZoomOut.setFont(font1)

        self.horizontalLayout_2.addWidget(self.btnZoomOut, 0, Qt.AlignmentFlag.AlignLeft)


        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        icon3 = QIcon()
        icon3.addFile(u":/assets/Login.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.inputTab, icon3, "")
        self.setupTab = QWidget()
        self.setupTab.setObjectName(u"setupTab")
        self.setupTab.setMinimumSize(QSize(787, 550))
        self.setupTab.setMaximumSize(QSize(787, 550))
        self.gridLayoutWidget = QWidget(self.setupTab)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 80, 781, 411))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)

        self.label_9 = QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)

        self.inputSaltPattern = QLineEdit(self.gridLayoutWidget)
        self.inputSaltPattern.setObjectName(u"inputSaltPattern")
        self.inputSaltPattern.setEnabled(False)
        self.inputSaltPattern.setMaximumSize(QSize(697, 25))

        self.gridLayout.addWidget(self.inputSaltPattern, 6, 1, 1, 1)

        self.inputAlphabet = QLineEdit(self.gridLayoutWidget)
        self.inputAlphabet.setObjectName(u"inputAlphabet")
        self.inputAlphabet.setEnabled(False)
        self.inputAlphabet.setMinimumSize(QSize(697, 25))
        self.inputAlphabet.setMaximumSize(QSize(697, 25))
        self.inputAlphabet.setFrame(True)
        self.inputAlphabet.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout.addWidget(self.inputAlphabet, 0, 1, 1, 1)

        self.inputKey = QLineEdit(self.gridLayoutWidget)
        self.inputKey.setObjectName(u"inputKey")
        self.inputKey.setEnabled(False)
        self.inputKey.setMinimumSize(QSize(697, 25))
        self.inputKey.setMaximumSize(QSize(697, 25))
        self.inputKey.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.gridLayout.addWidget(self.inputKey, 1, 1, 1, 1)

        self.label_6 = QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)

        self.label_4 = QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setTextFormat(Qt.TextFormat.PlainText)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)

        self.inputRounds = QLineEdit(self.gridLayoutWidget)
        self.inputRounds.setObjectName(u"inputRounds")
        self.inputRounds.setEnabled(False)
        self.inputRounds.setMaximumSize(QSize(697, 25))
        self.inputRounds.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhPreferNumbers)

        self.gridLayout.addWidget(self.inputRounds, 3, 1, 1, 1)

        self.inputSalt = QLineEdit(self.gridLayoutWidget)
        self.inputSalt.setObjectName(u"inputSalt")
        self.inputSalt.setEnabled(False)
        self.inputSalt.setMaximumSize(QSize(697, 25))

        self.gridLayout.addWidget(self.inputSalt, 5, 1, 1, 1)

        self.inputPlainText = QLineEdit(self.gridLayoutWidget)
        self.inputPlainText.setObjectName(u"inputPlainText")
        self.inputPlainText.setEnabled(False)
        self.inputPlainText.setMaximumSize(QSize(697, 25))

        self.gridLayout.addWidget(self.inputPlainText, 4, 1, 1, 1)

        self.label_5 = QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer, 2, 1, 1, 1)

        self.verticalLayoutWidget_4 = QWidget(self.setupTab)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(-1, 0, 781, 80))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(131, 17))
        font2 = QFont()
        font2.setPointSize(16)
        self.label.setFont(font2)
        self.label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)

        self.verticalLayout_4.addWidget(self.label, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.operationMode = QComboBox(self.verticalLayoutWidget_4)
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.addItem("")
        self.operationMode.setObjectName(u"operationMode")
        self.operationMode.setMinimumSize(QSize(231, 25))
        self.operationMode.setMaximumSize(QSize(231, 25))
        self.operationMode.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.verticalLayout_4.addWidget(self.operationMode, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayoutWidget = QWidget(self.setupTab)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 490, 781, 51))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.btnConfig = QPushButton(self.horizontalLayoutWidget)
        self.btnConfig.setObjectName(u"btnConfig")
        self.btnConfig.setEnabled(True)
        self.btnConfig.setMinimumSize(QSize(121, 25))
        self.btnConfig.setMaximumSize(QSize(121, 25))
        icon4 = QIcon()
        icon4.addFile(u":/assets/Configure.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnConfig.setIcon(icon4)

        self.horizontalLayout.addWidget(self.btnConfig)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.btnBruteForce = QPushButton(self.horizontalLayoutWidget)
        self.btnBruteForce.setObjectName(u"btnBruteForce")
        self.btnBruteForce.setEnabled(False)
        self.btnBruteForce.setMinimumSize(QSize(121, 25))
        self.btnBruteForce.setMaximumSize(QSize(121, 25))
        icon5 = QIcon()
        icon5.addFile(u":/assets/Crack.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnBruteForce.setIcon(icon5)
        self.btnBruteForce.setAutoDefault(False)
        self.btnBruteForce.setFlat(False)

        self.horizontalLayout.addWidget(self.btnBruteForce)

        self.btnDecode = QPushButton(self.horizontalLayoutWidget)
        self.btnDecode.setObjectName(u"btnDecode")
        self.btnDecode.setEnabled(False)
        self.btnDecode.setMinimumSize(QSize(121, 25))
        self.btnDecode.setMaximumSize(QSize(121, 25))
        icon6 = QIcon()
        icon6.addFile(u":/assets/Unlocked.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnDecode.setIcon(icon6)

        self.horizontalLayout.addWidget(self.btnDecode)

        self.btnEncode = QPushButton(self.horizontalLayoutWidget)
        self.btnEncode.setObjectName(u"btnEncode")
        self.btnEncode.setEnabled(False)
        self.btnEncode.setMinimumSize(QSize(121, 25))
        self.btnEncode.setMaximumSize(QSize(121, 25))
        icon7 = QIcon()
        icon7.addFile(u":/assets/Locked.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnEncode.setIcon(icon7)
        self.btnEncode.setCheckable(False)
        self.btnEncode.setChecked(False)

        self.horizontalLayout.addWidget(self.btnEncode, 0, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)

        self.tabWidget.addTab(self.setupTab, icon4, "")
        self.outputTab = QWidget()
        self.outputTab.setObjectName(u"outputTab")
        self.outputTab.setMinimumSize(QSize(787, 550))
        self.outputTab.setMaximumSize(QSize(787, 550))
        self.gridLayoutWidget_3 = QWidget(self.outputTab)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(0, 0, 791, 551))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.outputText = QPlainTextEdit(self.gridLayoutWidget_3)
        self.outputText.setObjectName(u"outputText")
        self.outputText.setMinimumSize(QSize(749, 439))
        self.outputText.setMaximumSize(QSize(749, 449))
        self.outputText.setFont(font)
        self.outputText.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.outputText.setReadOnly(True)
        self.outputText.setBackgroundVisible(False)

        self.gridLayout_3.addWidget(self.outputText, 2, 0, 1, 1)

        self.btnCopy = QPushButton(self.gridLayoutWidget_3)
        self.btnCopy.setObjectName(u"btnCopy")
        self.btnCopy.setMinimumSize(QSize(201, 25))
        self.btnCopy.setMaximumSize(QSize(201, 25))
        self.btnCopy.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCopy))
        self.btnCopy.setIcon(icon8)

        self.gridLayout_3.addWidget(self.btnCopy, 0, 0, 1, 1, Qt.AlignmentFlag.AlignHCenter)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.btnZoomIn_2 = QPushButton(self.gridLayoutWidget_3)
        self.btnZoomIn_2.setObjectName(u"btnZoomIn_2")
        self.btnZoomIn_2.setMaximumSize(QSize(31, 25))
        self.btnZoomIn_2.setFont(font1)
        self.btnZoomIn_2.setFlat(False)

        self.horizontalLayout_3.addWidget(self.btnZoomIn_2)

        self.btnZoomOut_2 = QPushButton(self.gridLayoutWidget_3)
        self.btnZoomOut_2.setObjectName(u"btnZoomOut_2")
        self.btnZoomOut_2.setMaximumSize(QSize(31, 25))
        self.btnZoomOut_2.setFont(font1)

        self.horizontalLayout_3.addWidget(self.btnZoomOut_2, 0, Qt.AlignmentFlag.AlignLeft)


        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)

        icon9 = QIcon()
        icon9.addFile(u":/assets/Logout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.outputTab, icon9, "")
        self.aboutTab = QWidget()
        self.aboutTab.setObjectName(u"aboutTab")
        self.verticalLayoutWidget_3 = QWidget(self.aboutTab)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(20, 10, 751, 521))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName(u"label_2")
        font3 = QFont()
        font3.setPointSize(26)
        self.label_2.setFont(font3)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.verticalLayout_3.addWidget(self.label_2)

        self.label_3 = QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_3)

        self.textBrowser = QTextBrowser(self.verticalLayoutWidget_3)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setOpenLinks(False)

        self.verticalLayout_3.addWidget(self.textBrowser)

        self.tabWidget.addTab(self.aboutTab, icon, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnBruteForce.clicked.connect(self.actionBrute.trigger)
        self.btnConfig.clicked.connect(self.actionConfig.trigger)
        self.btnDecode.clicked.connect(self.actionDecode.trigger)
        self.btnEncode.clicked.connect(self.actionEncode.trigger)
        self.operationMode.currentIndexChanged.connect(self.actionOperationChanged.trigger)
        self.btnCopy.clicked.connect(self.actionCopy.trigger)
        self.btnPaste.clicked.connect(self.actionPaste.trigger)
        self.btnZoomIn_2.clicked.connect(self.actionZoomIn.trigger)
        self.btnZoomIn.clicked.connect(self.actionZoomIn.trigger)
        self.btnZoomOut_2.clicked.connect(self.actionZoomOut.trigger)
        self.btnZoomOut.clicked.connect(self.actionZoomOut.trigger)

        self.tabWidget.setCurrentIndex(0)
        self.operationMode.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CRYPT GUI", None))
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionEncode.setText(QCoreApplication.translate("MainWindow", u"Encode", None))
        self.actionDecode.setText(QCoreApplication.translate("MainWindow", u"Decode", None))
        self.actionBrute.setText(QCoreApplication.translate("MainWindow", u"Brute", None))
        self.actionOperationChanged.setText(QCoreApplication.translate("MainWindow", u"OperationChanged", None))
#if QT_CONFIG(tooltip)
        self.actionOperationChanged.setToolTip(QCoreApplication.translate("MainWindow", u"OperationChanged", None))
#endif // QT_CONFIG(tooltip)
        self.actionConfig.setText(QCoreApplication.translate("MainWindow", u"Config", None))
#if QT_CONFIG(tooltip)
        self.actionConfig.setToolTip(QCoreApplication.translate("MainWindow", u"Configuration", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionConfig.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P, Ctrl+,", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomIn.setText(QCoreApplication.translate("MainWindow", u"ZoomIn", None))
#if QT_CONFIG(shortcut)
        self.actionZoomIn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+=", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomOut.setText(QCoreApplication.translate("MainWindow", u"ZoomOut", None))
#if QT_CONFIG(shortcut)
        self.actionZoomOut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(accessibility)
        self.inputTab.setAccessibleName(QCoreApplication.translate("MainWindow", u"&Input", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(tooltip)
        self.inputText.setToolTip(QCoreApplication.translate("MainWindow", u"Input area", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.inputText.setAccessibleName(QCoreApplication.translate("MainWindow", u"Input area", None))
#endif // QT_CONFIG(accessibility)
        self.inputText.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Input data to be encoded/decoded.", None))
#if QT_CONFIG(accessibility)
        self.btnPaste.setAccessibleName(QCoreApplication.translate("MainWindow", u"Paste from clipboard", None))
#endif // QT_CONFIG(accessibility)
        self.btnPaste.setText(QCoreApplication.translate("MainWindow", u"&Paste from Clipboard", None))
#if QT_CONFIG(shortcut)
        self.btnPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.btnZoomIn.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.btnZoomOut.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inputTab), QCoreApplication.translate("MainWindow", u"Input", None))
#if QT_CONFIG(tooltip)
        self.label_7.setToolTip(QCoreApplication.translate("MainWindow", u"Keywords: SALT, INPUT | \"SALT+INPUT\" means there would be a plus sign between salt and input before hashing.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_7.setWhatsThis(QCoreApplication.translate("MainWindow", u"How to use the salt before hashing.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_7.setAccessibleName(QCoreApplication.translate("MainWindow", u"Salt Pattern", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_7.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"How to use the salt before hashing.", None))
#endif // QT_CONFIG(accessibility)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Salt Pattern", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Rounds", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Plain Text", None))
#if QT_CONFIG(tooltip)
        self.inputSaltPattern.setToolTip(QCoreApplication.translate("MainWindow", u"Keywords: SALT, INPUT | \"SALT+INPUT\" means there would be a plus sign between salt and input before hashing.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.inputSaltPattern.setWhatsThis(QCoreApplication.translate("MainWindow", u"How to use the salt before hashing.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.inputSaltPattern.setAccessibleName(QCoreApplication.translate("MainWindow", u"Salt Pattern", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.inputSaltPattern.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"How to use the salt before hashing.", None))
#endif // QT_CONFIG(accessibility)
        self.inputSaltPattern.setText("")
        self.inputSaltPattern.setPlaceholderText(QCoreApplication.translate("MainWindow", u"How to use the salt before hashing. Default is SALT+INPUT", None))
#if QT_CONFIG(tooltip)
        self.inputAlphabet.setToolTip(QCoreApplication.translate("MainWindow", u"ABC...", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.inputAlphabet.setWhatsThis(QCoreApplication.translate("MainWindow", u"Alphabet to be used.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.inputAlphabet.setAccessibleName(QCoreApplication.translate("MainWindow", u"Alphabet", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.inputAlphabet.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Alphabet to be used.", None))
#endif // QT_CONFIG(accessibility)
        self.inputAlphabet.setInputMask("")
        self.inputAlphabet.setText("")
        self.inputAlphabet.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Alphabet to be used.", None))
#if QT_CONFIG(tooltip)
        self.inputKey.setToolTip(QCoreApplication.translate("MainWindow", u"Usually a number, word(s), or a set of chatacters", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.inputKey.setWhatsThis(QCoreApplication.translate("MainWindow", u"Key to be used for Encryption/Decryption.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.inputKey.setAccessibleName(QCoreApplication.translate("MainWindow", u"Key", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.inputKey.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Key to be used for Encryption/Decryption.", None))
#endif // QT_CONFIG(accessibility)
        self.inputKey.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Key to be used for Encryption/Decryption.", None))
#if QT_CONFIG(tooltip)
        self.label_6.setToolTip(QCoreApplication.translate("MainWindow", u"It is optional.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(QCoreApplication.translate("MainWindow", u"Salt to be used with the input.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_6.setAccessibleName(QCoreApplication.translate("MainWindow", u"Salt", None))
#endif // QT_CONFIG(accessibility)
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Salt", None))
#if QT_CONFIG(tooltip)
        self.label_4.setToolTip(QCoreApplication.translate("MainWindow", u"Alphabet to be used.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_4.setWhatsThis(QCoreApplication.translate("MainWindow", u"Alphabet to be used.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_4.setAccessibleName(QCoreApplication.translate("MainWindow", u"Alphabet", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_4.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Alphabet to be used.", None))
#endif // QT_CONFIG(accessibility)
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Alphabet", None))
#if QT_CONFIG(tooltip)
        self.inputRounds.setToolTip(QCoreApplication.translate("MainWindow", u"A number; The default changes based on selected operation.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.inputRounds.setWhatsThis(QCoreApplication.translate("MainWindow", u"Hash rounds", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.inputRounds.setAccessibleName(QCoreApplication.translate("MainWindow", u"Rounds", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.inputRounds.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"A number; The default changes based on selected operation.", None))
#endif // QT_CONFIG(accessibility)
        self.inputRounds.setPlaceholderText(QCoreApplication.translate("MainWindow", u"For bCrypt, Argon2, & PBKDF2", None))
#if QT_CONFIG(tooltip)
        self.inputSalt.setToolTip(QCoreApplication.translate("MainWindow", u"It is optional.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.inputSalt.setWhatsThis(QCoreApplication.translate("MainWindow", u"Salt to be used with the input.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.inputSalt.setAccessibleName(QCoreApplication.translate("MainWindow", u"Salt", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.inputSalt.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Salt to be used with the input.", None))
#endif // QT_CONFIG(accessibility)
        self.inputSalt.setPlaceholderText(QCoreApplication.translate("MainWindow", u"A salt for the hash; Could be left empty.", None))
#if QT_CONFIG(tooltip)
        self.inputPlainText.setToolTip(QCoreApplication.translate("MainWindow", u"Plain text of hashed input for verification.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.inputPlainText.setWhatsThis(QCoreApplication.translate("MainWindow", u"Plain text of hashed input for verification.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.inputPlainText.setAccessibleName(QCoreApplication.translate("MainWindow", u"Plain Text", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.inputPlainText.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Plain text of hashed input for verification.", None))
#endif // QT_CONFIG(accessibility)
        self.inputPlainText.setPlaceholderText(QCoreApplication.translate("MainWindow", u"For verification", None))
#if QT_CONFIG(tooltip)
        self.label_5.setToolTip(QCoreApplication.translate("MainWindow", u"Key to be used for Encryption/Decryption.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.label_5.setWhatsThis(QCoreApplication.translate("MainWindow", u"Key to be used for Encryption/Decryption.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.label_5.setAccessibleName(QCoreApplication.translate("MainWindow", u"Key", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_5.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Key to be used for Encryption/Decryption.", None))
#endif // QT_CONFIG(accessibility)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Key", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Operation", None))
        self.operationMode.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.operationMode.setItemText(1, QCoreApplication.translate("MainWindow", u"Base16", None))
        self.operationMode.setItemText(2, QCoreApplication.translate("MainWindow", u"Base32", None))
        self.operationMode.setItemText(3, QCoreApplication.translate("MainWindow", u"Base85", None))
        self.operationMode.setItemText(4, QCoreApplication.translate("MainWindow", u"Base64", None))
        self.operationMode.setItemText(5, QCoreApplication.translate("MainWindow", u"Caesar Cipher", None))
        self.operationMode.setItemText(6, QCoreApplication.translate("MainWindow", u"Morse Code", None))
        self.operationMode.setItemText(7, QCoreApplication.translate("MainWindow", u"Baconian Cipher", None))
        self.operationMode.setItemText(8, QCoreApplication.translate("MainWindow", u"Vigenere Cipher", None))
        self.operationMode.setItemText(9, QCoreApplication.translate("MainWindow", u"MD5", None))
        self.operationMode.setItemText(10, QCoreApplication.translate("MainWindow", u"MD5 CRYPT", None))
        self.operationMode.setItemText(11, QCoreApplication.translate("MainWindow", u"SHA256", None))
        self.operationMode.setItemText(12, QCoreApplication.translate("MainWindow", u"SHA256 CRYPT", None))
        self.operationMode.setItemText(13, QCoreApplication.translate("MainWindow", u"SHA512", None))
        self.operationMode.setItemText(14, QCoreApplication.translate("MainWindow", u"SHA512 CRYPT", None))
        self.operationMode.setItemText(15, QCoreApplication.translate("MainWindow", u"bCrypt", None))
        self.operationMode.setItemText(16, QCoreApplication.translate("MainWindow", u"Argon2", None))
        self.operationMode.setItemText(17, QCoreApplication.translate("MainWindow", u"NT Hash", None))
        self.operationMode.setItemText(18, QCoreApplication.translate("MainWindow", u"PBKDF2 SHA256", None))
        self.operationMode.setItemText(19, QCoreApplication.translate("MainWindow", u"PBKDF2 SHA512", None))

#if QT_CONFIG(tooltip)
        self.operationMode.setToolTip(QCoreApplication.translate("MainWindow", u"Operation (function) to apply on the input.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.operationMode.setWhatsThis(QCoreApplication.translate("MainWindow", u"Operations list", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.operationMode.setAccessibleName(QCoreApplication.translate("MainWindow", u"Operations list", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.operationMode.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Operation (function) to apply on the input.", None))
#endif // QT_CONFIG(accessibility)
        self.operationMode.setCurrentText(QCoreApplication.translate("MainWindow", u"None", None))
        self.operationMode.setPlaceholderText(QCoreApplication.translate("MainWindow", u"No Operation Chosen", None))
        self.btnConfig.setText(QCoreApplication.translate("MainWindow", u"&Config", None))
#if QT_CONFIG(shortcut)
        self.btnConfig.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+,", None))
#endif // QT_CONFIG(shortcut)
        self.btnBruteForce.setText(QCoreApplication.translate("MainWindow", u"&Brute Force", None))
        self.btnDecode.setText(QCoreApplication.translate("MainWindow", u"&Decode/Decrypt", None))
        self.btnEncode.setText(QCoreApplication.translate("MainWindow", u"&Encode/Encrypt", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setupTab), QCoreApplication.translate("MainWindow", u"Setup", None))
#if QT_CONFIG(tooltip)
        self.outputText.setToolTip(QCoreApplication.translate("MainWindow", u"Input area", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(accessibility)
        self.outputText.setAccessibleName(QCoreApplication.translate("MainWindow", u"Input area", None))
#endif // QT_CONFIG(accessibility)
        self.outputText.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Output result", None))
#if QT_CONFIG(accessibility)
        self.btnCopy.setAccessibleName(QCoreApplication.translate("MainWindow", u"Paste from clipboard", None))
#endif // QT_CONFIG(accessibility)
        self.btnCopy.setText(QCoreApplication.translate("MainWindow", u"&Copy to Clipboard", None))
#if QT_CONFIG(shortcut)
        self.btnCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.btnZoomIn_2.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom in the text area.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.btnZoomIn_2.setWhatsThis(QCoreApplication.translate("MainWindow", u"Zoom In", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btnZoomIn_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"Zoom In", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btnZoomIn_2.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Zoom in the text area.", None))
#endif // QT_CONFIG(accessibility)
        self.btnZoomIn_2.setText(QCoreApplication.translate("MainWindow", u"+", None))
#if QT_CONFIG(tooltip)
        self.btnZoomOut_2.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom out the text area.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.btnZoomOut_2.setWhatsThis(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.btnZoomOut_2.setAccessibleName(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.btnZoomOut_2.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Zoom out the text area.", None))
#endif // QT_CONFIG(accessibility)
        self.btnZoomOut_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputTab), QCoreApplication.translate("MainWindow", u"Output", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"CRYPT GUI", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Licenses", None))
        self.textBrowser.setDocumentTitle(QCoreApplication.translate("MainWindow", u"GNU General Public License v3.0", None))
        self.textBrowser.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><title>GNU General Public License v3.0</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CRYPT GUI, A Collection of tools, is licensed under GPL v3.0 Copyright (c) 2024 Ninja Left</p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CRYPT was built using Python 3.11, Qt Designer &amp; Pyside6.</p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; ma"
                        "rgin-right:0px; -qt-block-indent:0; text-indent:0px;\">Some functions used in this software are from <a href=\"https://github.com/TheAlgorithms/Python\"><span style=\" text-decoration: underline; color:#b85b6a;\">This Repository</span></a></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">and are licensed under MIT Copyright (c) 2016-2024 TheAlgorithms and contributors.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'monospace'; color:#ffffff;\">Icons:</span></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flaticon.com/free-icon"
                        "/configuration_9780271\"><span style=\" text-decoration: underline; color:#b85b6a;\">Configure icon by afif fudin - Flaticon</span></a></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flaticon.com/free-icon/login_5729989\"><span style=\" text-decoration: underline; color:#b85b6a;\">Login icon by FR_Media - Flaticon</span></a></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flaticon.com/free-icon/logout_5729988\"><span style=\" text-decoration: underline; color:#b85b6a;\">Logout icon by FR_Media - Flaticon</span></a></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flaticon.com/free-icon/lock_2549910\"><span style=\" text-decoration: underline; color:#b85b6a;\">Locked icon by Aswell Studio - Flaticon</span></"
                        "a></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flaticon.com/free-icon/unlock_2549951\"><span style=\" text-decoration: underline; color:#b85b6a;\">Unlocked icon by Aswell Studio - Flaticon</span></a></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flaticon.com/free-icon/unsecure_5690981\"><span style=\" text-decoration: underline; color:#b85b6a;\">Unsecure icon by juicy_fish - Flaticon</span></a></p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.flaticon.com/free-icon/search_1828057\"><span style=\" text-decoration: underline; color:#b85b6a;\">Search icon by Pixel Perfect - Flaticon</span></a></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), QCoreApplication.translate("MainWindow", u"About", None))
    # retranslateUi

